[2023-12-09T21:46:17.802+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sandbox.file_reader manual__2023-12-09T21:46:12+00:00 [queued]>
[2023-12-09T21:46:17.808+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sandbox.file_reader manual__2023-12-09T21:46:12+00:00 [queued]>
[2023-12-09T21:46:17.809+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-09T21:46:17.818+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): file_reader> on 2023-12-09 21:46:12+00:00
[2023-12-09T21:46:17.827+0000] {standard_task_runner.py:57} INFO - Started process 143 to run task
[2023-12-09T21:46:17.832+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sandbox', 'file_reader', 'manual__2023-12-09T21:46:12+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/sandbox.py', '--cfg-path', '/tmp/tmp4ndpe1pr']
[2023-12-09T21:46:17.836+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask file_reader
[2023-12-09T21:46:17.886+0000] {task_command.py:416} INFO - Running <TaskInstance: sandbox.file_reader manual__2023-12-09T21:46:12+00:00 [running]> on host 913299e645c2
[2023-12-09T21:46:17.948+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sandbox' AIRFLOW_CTX_TASK_ID='file_reader' AIRFLOW_CTX_EXECUTION_DATE='2023-12-09T21:46:12+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-09T21:46:12+00:00'
[2023-12-09T21:46:17.959+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/ebooklib/epub.py:1395: UserWarning: In the future version we will turn default option ignore_ncx to True.
  warnings.warn('In the future version we will turn default option ignore_ncx to True.')

[2023-12-09T21:46:17.961+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sandbox.py", line 34, in file_reader
    book = epub.read_epub(epub_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/ebooklib/epub.py", line 1768, in read_epub
    book = reader.load()
  File "/home/airflow/.local/lib/python3.8/site-packages/ebooklib/epub.py", line 1410, in load
    self._load()
  File "/home/airflow/.local/lib/python3.8/site-packages/ebooklib/epub.py", line 1714, in _load
    self.zf = zipfile.ZipFile(self.file_name, 'r', compression=zipfile.ZIP_DEFLATED, allowZip64=True)
  File "/usr/local/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: './carroll-alice-in-wonderland-illustrations.epub'
[2023-12-09T21:46:17.974+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=sandbox, task_id=file_reader, execution_date=20231209T214612, start_date=20231209T214617, end_date=20231209T214617
[2023-12-09T21:46:17.983+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task file_reader ([Errno 2] No such file or directory: './carroll-alice-in-wonderland-illustrations.epub'; 143)
[2023-12-09T21:46:18.005+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-09T21:46:18.025+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
